#
# Travis CI configuration file
#

# Based mostly upon https://github.com/BurntSushi/ripgrep/blob/master/.travis.yml

language: rust

env:
  global:
    - PROJECT_NAME=gisht
    - LINUX_ARCH=x86_64-unknown-linux-gnu
    - OSX_ARCH=x86_64-apple-darwin

os:
  - linux
rust:
  - stable
  - beta
  - nightly

matrix:
  include:
    - os: osx
      language: generic
      rust: stable
  # Test on nightly Rust, but failures there won't break the build.
  allow_failures:
    - rust: nightly


#
# Dependencies
#

# Linux
addons:
  apt:
    sources:
      - kalakris-cmake
    packages:
      - cmake

# OSX
before_install: |
  if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    . ./ci/travis/before_install-osx.sh
  fi

#
# Test script
#

install: |
  if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    pip install -r requirements-dev.txt
  else
    pip install --user -r requirements-dev.txt
  fi

script: inv test


#
# Release
#

before_deploy:
  # Specify the exact architecture to build the releases for.
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]];  then export ARCH="$LINUX_ARCH" ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]];    then export ARCH="$OSX_ARCH"   ; fi

  # Build the release bundles
  - . ./ci/travis/before_deploy.sh

deploy:
  provider: releases
  api_key:
    secure: TODO
  file: release/*
  file_glob: true
  # Retain the built release artifacts (otherwise there is nothing to deploy).
  skip_cleanup: true
  on:
    tags: true
    condition: TRAVIS_RUST_VERSION = stable
