#
# Travis CI configuration file
#

# Based mostly upon https://github.com/BurntSushi/ripgrep/blob/master/.travis.yml

language: rust

env:
  global:
    - PROJECT_NAME=gisht
    - LINUX_TARGET=x86_64-unknown-linux-gnu
    - OSX_TARGET=x86_64-apple-darwin

os:
  - linux
  - osx
rust:
  - stable
  - beta
  - nightly

matrix:
  # Test on nightly Rust, but failures there won't break the build.
  allow_failures:
    - rust: nightly


#
# Dependencies
#

# Linux
addons:
  apt:
    sources:
      - kalakris-cmake
    packages:
      - cmake

before_install: |
  # Specify the exact Rust build target.
  if [[ "$TRAVIS_OS_NAME" == "linux" ]];  then TARGET="$LINUX_TARGET" ; fi
  if [[ "$TRAVIS_OS_NAME" == "osx" ]];    then TARGET="$OSX_TARGET"   ; fi

  # OSX
  # (openssl incantations taken from https://github.com/sfackler/rust-openssl/issues/255)
  if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    brew update
    brew install openssl
    export OPENSSL_INCLUDE_DIR=`brew --prefix openssl`/include
    export OPENSSL_LIB_DIR=`brew --prefix openssl`/lib
    export DEP_OPENSSL_INCLUDE=`brew --prefix openssl`/include
  fi

#
# Test script
#

# Also on OSX, manually install Python
# and prepare virtualenv for Invoke tasks' dependencies.
# (This has to be done in install: section as per this comment:
#  https://github.com/travis-ci/travis-ci/issues/2312#issuecomment-247206351)
install: |
  if [[ "TRAVIS_OS_NAME" == "osx" ]]; then
    brew update
    brew install python
    virtualenv venv
    source venv/bin/activate
    pip install -r requirements-dev.txt
  else
    pip install --user -r requirements-dev.txt
  fi

script: inv test
