#
# Travis CI configuration file
#

# Based mostly upon https://github.com/BurntSushi/ripgrep/blob/master/.travis.yml

language: rust

env:
  global:
    - PROJECT_NAME=gisht
    - LINUX_ARCH=x86_64-unknown-linux-gnu
    - OSX_ARCH=x86_64-apple-darwin
    # For deploy: hook, to upload Homebrew formula back to the repo.
    - DEPLOY_ENC_LABEL=df5d3ee4baa7
    - COMMIT_AUTHOR_EMAIL=karol.kuczmarski@gmail.com

os:
  - linux
rust:
  - stable
  - beta
  - nightly

matrix:
  include:
    - os: osx
      language: generic
  # Test on nightly Rust, but failures there won't break the build.
  allow_failures:
    - rust: nightly


#
# Dependencies
#

# Linux
addons:
  apt:
    sources:
      - kalakris-cmake
    packages:
      - cmake
      # This is only needed for building release packages,
      # but we include it everywhere so we don't need `sudo: required`.
      - ruby
      - ruby-dev

# OSX
before_install: |
  if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    . ./ci/travis/before_install-osx.sh
  fi

#
# Test script
#

install: |
  if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    pip install -r requirements-dev.txt
  else
    pip install --user -r requirements-dev.txt
  fi

script: inv test


#
# Release
#

before_deploy:
  # Specify the exact architecture to build the releases for.
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]];  then export ARCH="$LINUX_ARCH" ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]];    then export ARCH="$OSX_ARCH"   ; fi

  # Build the release bundles
  - . ./ci/travis/before_deploy.sh

deploy:
  # Deploy build artifacts to GitHub Releases.
  - provider: releases
    api_key:
      secure: Wma7Fxr3prV6doGV/TUgMB9o1XB6DMsp/qzovWzgdTwE39ewOhRRRgI7Nwj5SvLGQHwX2AyWDnZQ7q853hDmhPKAVSowcUzNcI75LdNrwobdvuzZBt3lPSw5OZiJrMIXJ049oQLTuuP9GYDl/cDNTDjdLA1wgpiuAVXdt+G2C3yaH0MQD3XMrzc/fUH2d1dRPGHOMfMuoVXRumtSS62hKeueAgvH7jPefqX95vzAiIJRuGF9aFW1qRhQXYIYQSsPtq/Y6IEBCxDYx+qFGLfhVlA/OKAEYB6oPsD2tldhofN0buoXSiJTy1WeTuf+uJn1PXeJ4ck4Zl7/yAwo5LWpxy2+Vu6Cjyj3+c8kEtwF2YofBJLLCqHEOduYPMFeMOB46rKQSYT/RAR9Fj/DTAPQRwMThdaRJbp6Poh3AvRrAvUUe/C2NMftnF7bE0dnVTF9YTj+isZPc6yNDWyzN39iE7D8GA3f6LDdcIR0JdwpmzevyfmXyipq3CPpTJa+Yv/I6Vl6P0sNtBf4LPBufxfQfPGG4BH9lyvoxnLM/A2ipBEYJhXY3p/CgZSBbb3GXKLXXvObuMNaqApD6VXDWKJ+jx/W74cbWSkQ2jyexKcXMqlmjlMycDnly+rH8CzgayFwlE4iNFAQmScjNYxsGP9VI+HjuI1TOEi8zGn7XlELwXs=
    file: release/*-${TRAVIS_TAG}-*.*
    file_glob: true
    # Retain the built release artifacts (otherwise there is nothing to deploy).
    skip_cleanup: true
    on:
      tags: true
      # Deploy when artifacts from stable Rust (on Linux), or from the OSX build.
      condition: $TRAVIS_RUST_VERSION = stable || $TRAVIS_OS_NAME = osx
  # Commit & push the Homebrew formula (which is built in before_deploy:).
  - provider: script
    script: ./ci/travis/deploy-osx.sh
    skip_cleanup: true
    on:
      tags: true
      condition: $TRAVIS_OS_NAME = osx


#
# Meta
#

branches:
  only:
    # Run CI on pushes and PRs to master
    - master
    # Also on tags, so that deploys are triggered.
    # (This regex matches semantic versions like v1.2.3-rc4+2016.02.22)
    - /^\d+\.\d+\.\d+.*$/

git:
  # Don't set this to 1
  # (see note at https://docs.travis-ci.com/user/customizing-the-build#Git-Clone-Depth)
  depth: 5
