language: rust

rust:
  - nightly
  - beta
  - stable
os:
  - linux
  - osx

# Test on nightly Rust, but failures there won't break the build.
matrix:
  allow_failures:
    - rust: nightly

addons:
  apt:
    packages:
      - cmake

# Run the tests.
# TODO: make Travis run Invoke tasks instead
script: cargo test --no-fail-fast
