#
# Travis CI configuration file
#

# Based mostly upon https://github.com/BurntSushi/ripgrep/blob/master/.travis.yml

language: rust

env:
  global:
    - PROJECT_NAME=gisht
    - LINUX_TARGET=x86_64-unknown-linux-gnu
    - OSX_TARGET=x86_64-apple-darwin

os:
  - linux
  - osx
rust:
  - stable
  - beta
  - nightly

matrix:
  # Test on nightly Rust, but failures there won't break the build.
  allow_failures:
    - rust: nightly

# Specify the exact Rust build target.
before_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]];  then TARGET="$LINUX_TARGET" ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]];    then TARGET="$OSX_TARGET"   ; fi

#
# Dependencies
#

# Linux
addons:
  apt:
    sources:
      - kalakris-cmake
    packages:
      - cmake

# OSX
# (openssl incantations taken from https://github.com/sfackler/rust-openssl/issues/255)
before_install: |
  if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    brew update
    brew install openssl
    export OPENSSL_INCLUDE_DIR=`brew --prefix openssl`/include
    export OPENSSL_LIB_DIR=`brew --prefix openssl`/lib
    export DEP_OPENSSL_INCLUDE=`brew --prefix openssl`/include
  fi

#
# Test script
#

# TODO: make Travis run Invoke tasks instead
script: cargo test --no-fail-fast
