# gisht :: Homebrew formula
# AUTOGENERATED BY `inv release.brew` -- DO NOT EDIT!

class Gisht < Formula
  version '0.1.0'
  desc "Gists in the shell"
  homepage "https://github.com/Xion/gisht"
  url "https://github.com/Xion/gisht/releases/download/#{version}/gisht-#{version}-x86_64-apple-darwin.tar.gz"
  sha256 "d69cd71a0518eec3a09cd8b686beeb6a779bb06ac909a198f1c98c61fa1259b5"

  def install
    bin.install "gisht"
    # TODO: generate man pages
    # man1.install "gisht.1"
  end
end
