# gisht :: Homebrew formula
# AUTOGENERATED BY `inv release.brew` -- DO NOT EDIT!

class Gisht < Formula
  version '0.1.0'
  desc "Gists in the shell"
  homepage "https://github.com/Xion/gisht"
  url "https://github.com/Xion/gisht/releases/download/#{version}/gisht-#{version}-x86_64-apple-darwin.tar.gz"
  sha256 "63bced8a7d2789e7d5e9e4db119c18849de6e4b591cda6a03fd8b9b63504b690"

  def install
    bin.install "gisht"
    # TODO: generate man pages
    # man1.install "gisht.1"
  end
end
